# Generated by Django 5.2.7 on 2026-02-12 16:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('calorias_100g', models.IntegerField(default=0)),
                ('proteinas_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbos_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('grasas_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fibra_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('vitamina_a_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamina_c_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hierro_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('magnesio_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('potasio_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('zinc_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(max_length=500)),
                ('categoria', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
                ('detalles', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(blank=True, default='Venezuela', max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('medida_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medida_cuello', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medida_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('somatotipo', models.CharField(blank=True, choices=[('ECTO', 'Ectomorfo'), ('MESO', 'Mesomorfo'), ('ENDO', 'Endomorfo')], max_length=4)),
                ('notas_medicas', models.TextField(blank=True)),
                ('tipo_dieta', models.CharField(choices=[('OMNI', 'Omnívora'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('PALEO', 'Paleo'), ('OTRO', 'Personalizada')], default='OMNI', max_length=5)),
                ('frecuencia_comidas', models.CharField(choices=[('3G', '3 Comidas Grandes'), ('5P', '5 Comidas Pequeñas'), ('6+', 'Más de 6 snacks/comidas'), ('OMAD', 'Una comida al día')], default='3G', max_length=4)),
                ('objetivo', models.CharField(blank=True, choices=[('GANAR', 'Ganar masa muscular'), ('PERDER', 'Perder peso'), ('MANTENER', 'Mantenimiento/Salud')], max_length=10)),
                ('nivel_actividad', models.CharField(choices=[('SEDE', 'Sedentario'), ('LIGE', 'Ligero'), ('MODE', 'Moderado'), ('INTE', 'Intenso'), ('ATLE', 'Atleta')], default='SEDE', max_length=4)),
                ('horario_sueno', models.CharField(blank=True, max_length=100)),
                ('foto_perfil', models.BinaryField(blank=True, editable=True, null=True)),
                ('last_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('onboarding_completado', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario'), ('GUEST', 'Invitado')], default='USER', max_length=5)),
                ('ultimo_cambio_nombre', models.DateTimeField(blank=True, null=True)),
                ('alergias', models.ManyToManyField(blank=True, to='base.alergia')),
                ('condiciones_medicas', models.ManyToManyField(blank=True, to='base.condicionmedica')),
                ('disgustos', models.ManyToManyField(blank=True, related_name='disgustos_perfiles', to='base.gustos')),
                ('gustos', models.ManyToManyField(blank=True, related_name='gustos_perfiles', to='base.gustos')),
                ('intolerancias', models.ManyToManyField(blank=True, to='base.intolerancia')),
                ('medicamentos', models.ManyToManyField(blank=True, to='base.medicamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.IntegerField()),
                ('carbos', models.IntegerField()),
                ('grasas', models.IntegerField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('completada', models.BooleanField(default=True)),
                ('categoria', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack'), ('postre', 'Postre')], default='almuerzo', max_length=50)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas_diarias', to='base.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas/')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('calorias', models.IntegerField()),
                ('tiempo', models.CharField(max_length=50)),
                ('tiempo_minutos', models.IntegerField(default=30)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('proteinas', models.IntegerField(default=0)),
                ('carbos', models.IntegerField(default=0)),
                ('grasas', models.IntegerField(default=0)),
                ('tipo_dieta', models.CharField(choices=[('OMNI', 'Omnívora'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('PALEO', 'Paleo'), ('OTRO', 'Personalizada')], default='OMNI', max_length=10)),
                ('categoria', models.CharField(default='explorar', max_length=50)),
                ('presupuesto', models.CharField(default='Medio', max_length=20)),
                ('dificultad', models.CharField(default='Media', max_length=20)),
                ('ingredientes_count', models.IntegerField(default=0)),
                ('esta_aprobada', models.BooleanField(default=True)),
                ('perfil_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_propias', to='base.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_peso', to='base.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_acostarse', models.TimeField()),
                ('hora_levantarse', models.TimeField()),
                ('calidad', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sueno', to='base.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=200)),
                ('mensaje', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LEIDO', 'Leído'), ('REVISION', 'En Revisión'), ('IMPLEMENTADO', 'Implementado'), ('DESCARTADO', 'Descartado'), ('ARCHIVADO', 'Archivado')], default='PENDIENTE', max_length=15)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='base.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RACHA', 'Racha de Sesión'), ('REGISTRO', 'Nutrición'), ('AGUA', 'Hidratación'), ('OTRO', 'Bienestar')], max_length=20)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('icono', models.CharField(default='stars', max_length=50)),
                ('color_class', models.CharField(default='text-warning', max_length=20)),
                ('bg_class', models.CharField(default='bg-warning', max_length=20)),
                ('fecha_obtenido', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='base.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'titulo')},
            },
        ),
        migrations.CreateModel(
            name='LoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_streaks', to='base.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('perfil', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ArticuloGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.articulo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_guardados', to='base.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='CalificacionReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recetas', to='base.perfil')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='base.receta')),
            ],
            options={
                'unique_together': {('perfil', 'receta')},
            },
        ),
        migrations.CreateModel(
            name='RecetaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_favoritas', to='base.perfil')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.receta')),
            ],
            options={
                'unique_together': {('perfil', 'receta')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cantidad_vasos', models.IntegerField(default=0)),
                ('meta_vasos', models.IntegerField(default=8)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_agua', to='base.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('perfil', 'fecha')},
            },
        ),
    ]
