# Generated by Django 5.2.7 on 2026-01-25 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CondicionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gustos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(blank=True, default='Venezuela', max_length=100)),
                ('genero', models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura en cm', max_digits=5, null=True)),
                ('porcentaje_grasa', models.DecimalField(blank=True, decimal_places=1, help_text='% de grasa', max_digits=4, null=True)),
                ('somatotipo', models.CharField(blank=True, choices=[('ECTO', 'Ectomorfo'), ('MESO', 'Mesomorfo'), ('ENDO', 'Endomorfo')], max_length=4)),
                ('tipo_dieta', models.CharField(choices=[('OMNI', 'Omnívora (Todo)'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('KETO', 'Keto / Cetogénica'), ('PALEO', 'Paleo'), ('OTRO', 'Otro / Personalizado')], default='OMNI', max_length=5)),
                ('frecuencia_comidas', models.CharField(choices=[('3G', '3 Comidas Grandes'), ('5P', '5 Comidas Pequeñas'), ('6+', 'Más de 6 snacks/comidas'), ('OMAD', 'Una comida al día')], default='3G', max_length=4)),
                ('objetivo', models.CharField(choices=[('GANAR', 'Ganar masa muscular'), ('PERDER', 'Perder peso'), ('MANTENER', 'Mantenimiento/Salud')], max_length=10)),
                ('nivel_actividad', models.CharField(choices=[('SEDE', 'Sedentario (Poco o nada)'), ('LIGE', 'Ligero (1-3 días/sem)'), ('MODE', 'Moderado (3-5 días/sem)'), ('INTE', 'Intenso (6-7 días/sem)'), ('ATLE', 'Atleta / Muy intenso')], default='SEDE', max_length=4)),
                ('horario_sueno', models.CharField(blank=True, max_length=100)),
                ('foto_perfil', models.BinaryField(blank=True, editable=True, null=True)),
                ('last_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('onboarding_completado', models.BooleanField(default=False)),
                ('alergias', models.ManyToManyField(blank=True, to='base.alergia')),
                ('condiciones_medicas', models.ManyToManyField(blank=True, to='base.condicionmedica')),
                ('gustos', models.ManyToManyField(blank=True, related_name='gustos_perfiles', to='base.gustos')),
                ('intolerancias', models.ManyToManyField(blank=True, to='base.intolerancia')),
                ('medicamentos', models.ManyToManyField(blank=True, to='base.medicamento')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_peso', to='base.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSueno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_acostarse', models.TimeField()),
                ('hora_levantarse', models.TimeField()),
                ('calidad', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Del 1 al 5')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_sueno', to='base.perfil')),
            ],
        ),
    ]
