# Generated by Django 4.2.27 on 2026-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('GANAR', 'Ganar masa muscular'), ('PERDER', 'Perder peso'), ('MANTENER', 'Mantenimiento/Salud')], max_length=10),
        ),
    ]
