# Generated by Django 5.2.7 on 2026-02-02 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_perfil_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen_url', models.URLField(max_length=500)),
                ('categoria', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_url', models.URLField(max_length=500)),
                ('calorias', models.IntegerField()),
                ('tiempo', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('proteinas', models.CharField(max_length=50)),
                ('carbos', models.CharField(max_length=50)),
                ('grasas', models.CharField(max_length=50)),
                ('tipo_dieta', models.CharField(choices=[('OMNI', 'Omnívora (Todo)'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('KETO', 'Keto / Cetogénica'), ('PALEO', 'Paleo'), ('OTRO', 'Otro / Personalizado')], default='OMNI', max_length=10)),
                ('categoria', models.CharField(default='explorar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.articulo')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_guardados', to='base.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'articulo')},
            },
        ),
        migrations.CreateModel(
            name='RecetaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_favoritas', to='base.perfil')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.receta')),
            ],
            options={
                'unique_together': {('perfil', 'receta')},
            },
        ),
    ]
