# Generated by Django 5.2.8 on 2026-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_articulo_receta_articuloguardado_recetafavorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('USER', 'Usuario'), ('GUEST', 'Invitado')], default='USER', max_length=5),
        ),
    ]
