# Generated by Django 4.2.27 on 2026-02-04 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_articulo_receta_articuloguardado_recetafavorita'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.IntegerField(default=0)),
                ('carbos', models.IntegerField(default=0)),
                ('grasas', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas_diarias', to='base.perfil')),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.receta')),
            ],
        ),
    ]
