# Generated by Django 4.2.27 on 2026-02-04 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comidadiaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.TextField(blank=True, help_text='Lista de ingredientes'),
        ),
        migrations.AddField(
            model_name='receta',
            name='perfil_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_creadas', to='base.perfil'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='calorias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='carbos',
            field=models.CharField(default='0g', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Pasos de preparación'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='grasas',
            field=models.CharField(default='0g', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='proteinas',
            field=models.CharField(default='0g', max_length=50),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo',
            field=models.CharField(default='20 min', max_length=50),
        ),
    ]
