# Generated by Django 5.2.8 on 2026-02-04 21:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_perfil_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('calorias', models.IntegerField()),
                ('proteinas', models.IntegerField()),
                ('carbos', models.IntegerField()),
                ('grasas', models.IntegerField()),
                ('hora', models.TimeField()),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('completada', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas_diarias', to='base.perfil')),
            ],
        ),
    ]
