# Generated by Django 4.2.27 on 2026-02-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_receta_ingredientes_receta_perfil_creador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='ingredientes',
        ),
        migrations.AlterField(
            model_name='receta',
            name='calorias',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='receta',
            name='carbos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='grasas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='perfil_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_propias', to='base.perfil'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='proteinas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo',
            field=models.CharField(max_length=50),
        ),
    ]
