# Generated by Django 5.2.8 on 2026-02-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_comidadiaria'),
        ('base', '0006_remove_receta_ingredientes_alter_receta_calorias_and_more'),
    ]

    operations = [
    ]
