# Generated by Django 5.2.8 on 2026-02-04 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_merge_20260204_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_streaks', to='base.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('perfil', 'fecha')},
            },
        ),
    ]
