# Generated by Django 5.2.8 on 2026-02-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_loginstreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='medida_cadera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Circunferencia cadera en cm (Mujeres)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='medida_cintura',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Circunferencia cintura en cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='medida_cuello',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Circunferencia cuello en cm', max_digits=5, null=True),
        ),
    ]
