# Generated by Django 5.2.8 on 2026-02-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_perfil_medida_cadera_perfil_medida_cintura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='notas_medicas',
            field=models.TextField(blank=True, help_text='Notas médicas adicionales o especificaciones.'),
        ),
    ]
