# Generated by Django 5.2.8 on 2026-02-05 01:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_perfil_notas_medicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cantidad_vasos', models.IntegerField(default=0)),
                ('meta_vasos', models.IntegerField(default=8)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_agua', to='base.perfil')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('perfil', 'fecha')},
            },
        ),
    ]
