# Generated by Django 5.2.7 on 2026-02-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_articulo_vistas_receta_vistas_auditoria_sugerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencia',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='vistas',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='vistas',
        ),
        migrations.DeleteModel(
            name='Auditoria',
        ),
        migrations.DeleteModel(
            name='Sugerencia',
        ),
    ]
