# Generated by Django 5.2.7 on 2026-02-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_sugerencia_perfil_remove_articulo_vistas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gustos',
            name='le_gusta',
            field=models.BooleanField(default=True),
        ),
    ]
