# Generated by Django 5.2.7 on 2026-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_gustos_le_gusta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comidadiaria',
            name='categoria',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snack', 'Snack'), ('postre', 'Postre')], default='almuerzo', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_dieta',
            field=models.CharField(choices=[('OMNI', 'Omnívora (Todo)'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('PALEO', 'Paleo'), ('OTRO', 'Otro / Personalizado')], default='OMNI', max_length=5),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_dieta',
            field=models.CharField(choices=[('OMNI', 'Omnívora (Todo)'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('PALEO', 'Paleo'), ('OTRO', 'Otro / Personalizado')], default='OMNI', max_length=10),
        ),
    ]
