# Generated by Django 5.2.7 on 2026-02-08 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_comidadiaria_categoria_alter_perfil_tipo_dieta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='medida_cadera',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='medida_cintura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='medida_cuello',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nivel_actividad',
            field=models.CharField(choices=[('SEDE', 'Sedentario'), ('LIGE', 'Ligero'), ('MODE', 'Moderado'), ('INTE', 'Intenso'), ('ATLE', 'Atleta')], default='SEDE', max_length=4),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='notas_medicas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='porcentaje_grasa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='registrosueno',
            name='calidad',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.CreateModel(
            name='CalificacionReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_recetas', to='base.perfil')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='base.receta')),
            ],
            options={
                'unique_together': {('perfil', 'receta')},
            },
        ),
    ]
