# Generated by Django 5.2.7 on 2026-02-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_perfil_altura_alter_perfil_medida_cadera_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gustos',
            name='le_gusta',
        ),
        migrations.AddField(
            model_name='perfil',
            name='disgustos',
            field=models.ManyToManyField(blank=True, related_name='disgustos_perfiles', to='base.gustos'),
        ),
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(default='Media', max_length=20),
        ),
        migrations.AddField(
            model_name='receta',
            name='presupuesto',
            field=models.CharField(default='Medio', max_length=20),
        ),
    ]
