# Generated by Django 5.2.7 on 2026-02-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_gustos_le_gusta_perfil_disgustos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='ingredientes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_dieta',
            field=models.CharField(choices=[('OMNI', 'Omnívora'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('PALEO', 'Paleo'), ('OTRO', 'Personalizada')], default='OMNI', max_length=5),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tipo_dieta',
            field=models.CharField(choices=[('OMNI', 'Omnívora'), ('VEGE', 'Vegetariana'), ('VEGA', 'Vegana'), ('PALEO', 'Paleo'), ('OTRO', 'Personalizada')], default='OMNI', max_length=10),
        ),
    ]
