# Generated by Django 5.2.7 on 2026-02-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_receta_ingredientes_count_alter_perfil_tipo_dieta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tiempo_minutos',
            field=models.IntegerField(default=30),
        ),
    ]
