# Generated by Django 5.2.7 on 2026-02-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_receta_esta_aprobada_logactividad_sugerencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencia',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
    ]
