# Generated by Django 5.2.7 on 2026-02-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_sugerencia_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ultimo_cambio_nombre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LEIDO', 'Leído'), ('REVISION', 'En Revisión'), ('IMPLEMENTADO', 'Implementado'), ('DESCARTADO', 'Descartado'), ('ARCHIVADO', 'Archivado')], default='PENDIENTE', max_length=15),
        ),
    ]
