# Generated by Django 5.2.7 on 2026-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_perfil_ultimo_cambio_nombre_alter_sugerencia_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('calorias_100g', models.IntegerField(default=0)),
                ('proteinas_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('carbos_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('grasas_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('fibra_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('vitamina_a_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vitamina_c_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hierro_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('magnesio_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('potasio_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('zinc_mg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
