# Generated by Django 5.2.7 on 2026-02-12 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RACHA', 'Racha de Sesión'), ('REGISTRO', 'Nutrición'), ('AGUA', 'Hidratación'), ('OTRO', 'Bienestar')], max_length=20)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('icono', models.CharField(default='stars', max_length=50)),
                ('color_class', models.CharField(default='text-warning', max_length=20)),
                ('bg_class', models.CharField(default='bg-warning', max_length=20)),
                ('fecha_obtenido', models.DateField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to='base.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'titulo')},
            },
        ),
    ]
